### Get Product 
GET http://localhost:8081/api/v2/product HTTP/1.1
x-access-token : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWI2NTU1NjE4ZGUwMmE0ZGFiZjFlNCIsImxldmVsIjoibm9ybWFsIiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTYwNTA2ODI0OCwiZXhwIjoxNjA1MDY5MjQ4LCJhdWQiOiJodHRwOi8vY29kZW1vYmlsZXMuY29tIiwiaXNzIjoiQ29kZU1vYmlsZXMgTHRkIiwic3ViIjoiY2hhaXlhc2l0LnRAZ21haWwuY29tIn0.HEU2a1bo5_3cPWb_HRZrXkTFPFFqZcBlbnwkuSBKMhZuGhv7Y8C6_PlPeHSju47dkm_FyrHw6bws0H_AtgvSeNkih4obyB1jdou_vj3QTL_TGgk3Ts7_nbZQtHyF21f7LXmS5FkzvGmXACB1KbqNFnNgI1547xkmZBqb9Omtlak


### Get Product (string query) 
GET http://localhost:8081/api/v2/product?token1=t1&token2=t2&token3=t3 HTTP/1.1


### Create 
POST http://localhost:8081/api/v2/product HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password" : "1234"
}